//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factories
    {
        public int groupCode { get; set; }
        public int factoryCode { get; set; }
        public string factoryName { get; set; }
    
        public virtual Groups Groups { get; set; }
    }
}
